apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: object-detection-test25100601
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: object-detection-test25100601
  name: object-detection-test25100601
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: object-detection-test25100601
    weight: 100
  wildcardPolicy: None
